### ISSUE TITLE
framedim parameter broken

### ISSUE THREAD

**Issue by martinclaus** [jbusecke/xmovie#46]
The `framedim` parameter of the `Movie` class does not seem to work. Here is a minimal example that fails for xmovie 0.1.0 installed via conda-forge:
```python
import xarray as xr
import xmovie

ds = xr.tutorial.open_dataset('air_temperature').isel(time=slice(0, 150)).rename({'time': "TIME"})
mov = xmovie.Movie(ds.air, framedim="TIME")
mov.save('animation.gif', overwrite_existing=True)
```

There seems to be the assumption that the dataset must have a dimension with name `time`. This seems like a rather strong assumption.

**Comment by jbusecke** [comment]
Dear @martinclaus, sorry for the late reply. I think this issue was fixed in #32.

I just tried this with the upstream version (Installed via `pip install git+https://github.com/jbusecke/xmovie.git`) and it worked for me. Could you confirm your version and installation method?

The release of this should have been made a while ago but is blocked by #45.

**Comment by martinclaus** [comment]
Sorry, I have not searched the merge requests before creating the issue. I have installed xmovie from conda-forge. The version is 0.1.0. I guess that means you can close the issue. Anyway, great package!

**Comment by jbusecke** [comment]
I'll try to fix that PyPI release (which will then trigger a new version on conda-forge). 

> Anyway, great package!

Vielen Lieben Dank, und Gruesse nach Kiel!
