### ISSUE TITLE
Customize framerates

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/xmovie#5]
It would be nice to have options to adjust the framerate. 
In some circumstances (low time resolution) people might prefer a ‘stop motion’ style animation.

**Comment by tomchor** [comment]
I was just about to post this issue here. The only reason why I'm not using this package is because I can't customize the framerate. Maybe just allowing us to pass keyword arguments to ffmpeg would be enough.

**Comment by jbusecke** [comment]
Thanks for checking out xmovie. This feedback is very helpful to me. 

That should be easy enough to implement. 

I could easily add a keyword `framerate` to the `Movie` class and parse it to the ffmpeg routine. Do you think it would be better to do this (I think its more user friendly, especially for beginners) or just give a `ffmpeg_options` keyword (more flexible but also potentially more error prone)? Finally would you prefer to have different framerates for the movie and gif creation?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tomchor** [comment]
@jbusecke IMO ideally there would be the user-friendly `framerate` option on the `Movie` class along with an option to give other args to ffmpeg (for more advanced users). This is what `matplotlib` does with its `ffmpegWriter`. But I think you could start only with the framerate option, since this already solves probably 95% of the demand.

I'm not sure about the different framerates for movie and gif creation. I've never created a gif so I really have no opinion on that.

Thanks a lot for looking into this!

**Comment by jbusecke** [comment]
I started a PR but need to complete the testing. Bear with me, but customizable framerates should be available soon 😀

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jbusecke** [comment]
Ok I have an implementation that allows you to specify `framerate` and `gif_framerate` in `Movie.save` #15 .
It also allows the more advanced user to pass `ffmpeg_options` to specify bitrate and presets.

Just waiting for the CI to pass and then I can merge it.

**Comment by tomchor** [comment]
Awesome! Thanks for doing this this fast

**Comment by jbusecke** [comment]
Closing via #15
