### ISSUE TITLE
How can I use ProPlot?

### ISSUE THREAD

**Issue by iuryt** [jbusecke/xmovie#92]
Hi,

I noticed that in order to give a custom function, I need to assume that the `fig` object already exist.
Can I give a `fig` object?

I would like to use [ProPlot](https://proplot.readthedocs.io/en/latest/index.html).

**Comment by jbusecke** [comment]
Oh interesting question. I have never used ProPlot, could you give a simple example of how you would create a figure in there?

**Comment by iuryt** [comment]
I think they basically use matplotlib to create publication-quality graphics without having to edit styles and setting up everything by yourself at every beginning of code. As far as I know, they only create new attributes and methods to matplotlib's classes. So it should be totally compatible to xmovie, right?

```python
# Simple subplot
import numpy as np
import proplot as pplt
state = np.random.RandomState(51423)
data = 2 * (state.rand(100, 5) - 0.5).cumsum(axis=0)
fig, ax = pplt.subplot(suptitle='Single subplot', xlabel='x axis', ylabel='y axis')
# fig = pplt.figure(suptitle='Single subplot')  # equivalent to above
# ax = fig.subplot(xlabel='x axis', ylabel='y axis')
ax.plot(data, lw=2)
```

![image](https://user-images.githubusercontent.com/5797727/161572426-469c44f5-c8e9-45cc-b264-343f0fabf813.png)

**Comment by jbusecke** [comment]
Sorry for the late answer here. 
The problem here is that the creation of a figure and the creation of the axis are separated in the xmovie code. The latter can be customized like [this](https://xmovie.readthedocs.io/en/latest/), but the former is currently pretty hardcoded [here](https://github.com/jbusecke/xmovie/blob/f69ed6d6813e230f96188deec62e66aa7db3a926/xmovie/core.py#L329).
This would be quite a bit more complex to change.

**Comment by iuryt** [comment]
I see. So this is not as simple as just adding an option for the user to give a `Figure` object beforehand.

**Comment by jbusecke** [comment]
Not really because the figure gets created with the specific width and height [from the movie object](https://github.com/jbusecke/xmovie/blob/f69ed6d6813e230f96188deec62e66aa7db3a926/xmovie/core.py#L329).
Unless you can somehow 'promote' a plt.figure to a pplot.figure, this would mean you would have to change the creation code in the lines above. Not imposible though, but if we decide to implement that, we might want to think if we want to make the scope more general. Happy to discuss this further! I have to note though that my plate is currently quite full, so an implementation might take a bit of time, just wanted to be up front about that.

**Comment by iuryt** [comment]
No problem at all, I just decided to move forward and continue coding by myself the functionalities available in ProPlot, so I am not using it anymore.
Idk if we should close this or just keep it in case someone else wants to give a `fig` as an input as well.

**Comment by jbusecke** [comment]
I will close it for now. For anyone stumbling across this, please feel free to reopen.
